import pandas as pd

corona = pd.read_excel("datasets/corona_nodes.xlsx")
influenza = pd.read_excel("datasets/influenza_nodes.xlsx")

corona_eig = pd.read_excel("outputs/corona_centrality_measures/eigenvector_centrality.xlsx")  
corona_eig = corona_eig.sort_values(by=['Node'],ascending=True)
influenza_eig = pd.read_excel("outputs/influenza_centrality_measures/eigenvector_centrality.xlsx")  
influenza_eig = influenza_eig.sort_values(by=['Node'],ascending=True)

corona_eignp = pd.read_excel("outputs/corona_centrality_measures/eigenvector_centrality_numpy.xlsx")  
corona_eignp = corona_eignp.sort_values(by=['Node'],ascending=True)
influenza_eignp = pd.read_excel("outputs/influenza_centrality_measures/eigenvector_centrality_numpy.xlsx")  
influenza_eignp = influenza_eignp.sort_values(by=['Node'],ascending=True)

corona_sub = pd.read_excel("outputs/corona_centrality_measures/subgraph_centrality.xlsx")  
corona_sub = corona_sub.sort_values(by=['Node'],ascending=True)
influenza_sub = pd.read_excel("outputs/influenza_centrality_measures/subgraph_centrality.xlsx")  
influenza_sub = influenza_sub.sort_values(by=['Node'],ascending=True)

corona_katznp = pd.read_excel("outputs/corona_centrality_measures/katz_centrality_numpy.xlsx")  
corona_katznp = corona_katznp.sort_values(by=['Node'],ascending=True)
influenza_katznp = pd.read_excel("outputs/influenza_centrality_measures/katz_centrality_numpy.xlsx")  
influenza_katznp = influenza_katznp.sort_values(by=['Node'],ascending=True)

corona_subexp = pd.read_excel("outputs/corona_centrality_measures/subgraph_centrality_exp.xlsx")
corona_subexp = corona_subexp.sort_values(by=['Node'],ascending=True)
influenza_subexp = pd.read_excel("outputs/influenza_centrality_measures/subgraph_centrality_exp.xlsx")
influenza_subexp = influenza_subexp.sort_values(by=['Node'],ascending=True)

corona_deg = pd.read_excel("outputs/corona_centrality_measures/degree_centrality.xlsx")
corona_deg = corona_deg.sort_values(by=['Node'],ascending=True)
influenza_deg = pd.read_excel("outputs/influenza_centrality_measures/degree_centrality.xlsx")
influenza_deg = influenza_deg.sort_values(by=['Node'],ascending=True)

corona_lap = pd.read_excel("outputs/corona_centrality_measures/laplacian_centrality.xlsx")
corona_lap = corona_lap.sort_values(by=['Node'],ascending=True)
influenza_lap = pd.read_excel("outputs/influenza_centrality_measures/laplacian_centrality.xlsx")
influenza_lap = influenza_lap.sort_values(by=['Node'],ascending=True)

corona_clo = pd.read_excel("outputs/corona_centrality_measures/closeness_centrality.xlsx")
corona_clo = corona_clo.sort_values(by=['Node'],ascending=True)
influenza_clo = pd.read_excel("outputs/influenza_centrality_measures/closeness_centrality.xlsx")
influenza_clo = influenza_clo.sort_values(by=['Node'],ascending=True)

corona_har = pd.read_excel("outputs/corona_centrality_measures/harmonic_centrality.xlsx")
corona_har = corona_har.sort_values(by=['Node'],ascending=True)
influenza_har = pd.read_excel("outputs/influenza_centrality_measures/harmonic_centrality.xlsx")
influenza_har = influenza_har.sort_values(by=['Node'],ascending=True)

corona_bet = pd.read_excel("outputs/corona_centrality_measures/betweenness_centrality.xlsx")
corona_bet = corona_bet.sort_values(by=['Node'],ascending=True)
influenza_bet = pd.read_excel("outputs/influenza_centrality_measures/betweenness_centrality.xlsx")
influenza_bet = influenza_bet.sort_values(by=['Node'],ascending=True)

corona_dec = pd.read_excel("outputs/corona_centrality_measures/decay_centrality.xlsx")
corona_dec = corona_dec.sort_values(by=['Node'],ascending=True)
influenza_dec = pd.read_excel("outputs/influenza_centrality_measures/decay_centrality.xlsx")
influenza_dec = influenza_dec.sort_values(by=['Node'],ascending=True)

corona_ecc = pd.read_excel("outputs/corona_centrality_measures/eccentricity.xlsx")
corona_ecc = corona_ecc.sort_values(by=['Node'],ascending=True)
influenza_ecc = pd.read_excel("outputs/influenza_centrality_measures/eccentricity.xlsx")
influenza_ecc = influenza_ecc.sort_values(by=['Node'],ascending=True)

corona_rad = pd.read_excel("outputs/corona_centrality_measures/radiality_centrality.xlsx")
corona_rad = corona_rad.sort_values(by=['Node'],ascending=True)
influenza_rad = pd.read_excel("outputs/influenza_centrality_measures/radiality_centrality.xlsx")
influenza_rad = influenza_rad.sort_values(by=['Node'],ascending=True)

corona_cfc = pd.read_excel("outputs/corona_centrality_measures/current_flow_closeness_centrality.xlsx")
corona_cfc = corona_cfc.sort_values(by=['Node'],ascending=True)
influenza_cfc = pd.read_excel("outputs/influenza_centrality_measures/current_flow_closeness_centrality.xlsx")
influenza_cfc = influenza_cfc.sort_values(by=['Node'],ascending=True)

corona_cfcinfo = pd.read_excel("outputs/corona_centrality_measures/information_centrality.xlsx")
corona_cfcinfo = corona_cfcinfo.sort_values(by=['Node'],ascending=True)
influenza_cfcinfo = pd.read_excel("outputs/influenza_centrality_measures/information_centrality.xlsx")
influenza_cfcinfo = influenza_cfcinfo.sort_values(by=['Node'],ascending=True)

corona_cfb = pd.read_excel("outputs/corona_centrality_measures/current_flow_betweenness_centrality.xlsx")
corona_cfb = corona_cfb.sort_values(by=['Node'],ascending=True)
influenza_cfb = pd.read_excel("outputs/influenza_centrality_measures/current_flow_betweenness_centrality.xlsx")
influenza_cfb = influenza_cfb.sort_values(by=['Node'],ascending=True)

corona_acf = pd.read_excel("outputs/corona_centrality_measures/approximate_current_flow_betweenness_centrality.xlsx")
corona_acf = corona_acf.sort_values(by=['Node'],ascending=True)
influenza_acf = pd.read_excel("outputs/influenza_centrality_measures/approximate_current_flow_betweenness_centrality.xlsx")
influenza_acf = influenza_acf.sort_values(by=['Node'],ascending=True)

corona_cbc = pd.read_excel("outputs/corona_centrality_measures/communicability_betweenness_centrality.xlsx")
corona_cbc = corona_cbc.sort_values(by=['Node'],ascending=True)
influenza_cbc = pd.read_excel("outputs/influenza_centrality_measures/communicability_betweenness_centrality.xlsx")
influenza_cbc = influenza_cbc.sort_values(by=['Node'],ascending=True)

corona_lc = pd.read_excel("outputs/corona_centrality_measures/load_centrality.xlsx")
corona_lc = corona_lc.sort_values(by=['Node'],ascending=True)
influenza_lc = pd.read_excel("outputs/influenza_centrality_measures/load_centrality.xlsx")
influenza_lc = influenza_lc.sort_values(by=['Node'],ascending=True)

corona_pr = pd.read_excel("outputs/corona_centrality_measures/pagerank.xlsx")
corona_pr = corona_pr.sort_values(by=['Node'],ascending=True)
influenza_pr = pd.read_excel("outputs/influenza_centrality_measures/pagerank.xlsx")
influenza_pr = influenza_pr.sort_values(by=['Node'],ascending=True)

corona_soc = pd.read_excel("outputs/corona_centrality_measures/second_order_centrality.xlsx")
corona_soc = corona_soc.sort_values(by=['Node'],ascending=True)
influenza_soc = pd.read_excel("outputs/influenza_centrality_measures/second_order_centrality.xlsx")
influenza_soc = influenza_soc.sort_values(by=['Node'],ascending=True)

corona_pb = pd.read_excel("outputs/corona_centrality_measures/proximal_betweenness.xlsx")
influenza_pb = pd.read_excel("outputs/influenza_centrality_measures/proximal_betweenness.xlsx")

corona_katz = pd.read_excel("outputs/corona_centrality_measures/katz_centrality.xlsx")
influenza_katz = pd.read_excel("outputs/influenza_centrality_measures/katz_centrality.xlsx")

corona_brc = pd.read_excel("outputs/corona_centrality_measures/beta_reach_centrality.xlsx")
influenza_brc = pd.read_excel("outputs/influenza_centrality_measures/beta_reach_centrality.xlsx")




corona_dt = corona.merge(corona_eig)
corona_dt = corona_dt.merge(corona_eignp)
corona_dt = corona_dt.merge(corona_sub)
corona_dt = corona_dt.merge(corona_katznp)
corona_dt = corona_dt.merge(corona_subexp)
corona_dt = corona_dt.merge(corona_deg)
corona_dt = corona_dt.merge(corona_lap)
corona_dt = corona_dt.merge(corona_clo)
corona_dt = corona_dt.merge(corona_har)
corona_dt = corona_dt.merge(corona_bet)
corona_dt = corona_dt.merge(corona_dec)
corona_dt = corona_dt.merge(corona_ecc)
corona_dt = corona_dt.merge(corona_rad)
corona_dt = corona_dt.merge(corona_cfc)
corona_dt = corona_dt.merge(corona_cfcinfo)
corona_dt = corona_dt.merge(corona_cfb)
corona_dt = corona_dt.merge(corona_acf)
corona_dt = corona_dt.merge(corona_cbc)
corona_dt = corona_dt.merge(corona_lc)
corona_dt = corona_dt.merge(corona_pr)
corona_dt = corona_dt.merge(corona_soc)
corona_dt = corona_dt.merge(corona_pb)
corona_dt = corona_dt.merge(corona_katz)
corona_dt = corona_dt.merge(corona_brc)

influenza_dt = influenza.merge(influenza_eig)
influenza_dt = influenza_dt.merge(influenza_eignp)
influenza_dt = influenza_dt.merge(influenza_sub)
influenza_dt = influenza_dt.merge(influenza_katznp)
influenza_dt = influenza_dt.merge(influenza_subexp)
influenza_dt = influenza_dt.merge(influenza_deg)
influenza_dt = influenza_dt.merge(influenza_lap)
influenza_dt = influenza_dt.merge(influenza_clo)
influenza_dt = influenza_dt.merge(influenza_har)
influenza_dt = influenza_dt.merge(influenza_bet)
influenza_dt = influenza_dt.merge(influenza_dec)
influenza_dt = influenza_dt.merge(influenza_ecc)
influenza_dt = influenza_dt.merge(influenza_rad)
influenza_dt = influenza_dt.merge(influenza_cfc)
influenza_dt = influenza_dt.merge(influenza_cfcinfo)
influenza_dt = influenza_dt.merge(influenza_cfb)
influenza_dt = influenza_dt.merge(influenza_acf)
influenza_dt = influenza_dt.merge(influenza_cbc)
influenza_dt = influenza_dt.merge(influenza_lc)
influenza_dt = influenza_dt.merge(influenza_pr)
influenza_dt = influenza_dt.merge(influenza_soc)
influenza_dt = influenza_dt.merge(influenza_pb)
influenza_dt = influenza_dt.merge(influenza_katz)
influenza_dt = influenza_dt.merge(influenza_brc)
corona_dt.to_excel('outputs/corona_centrality_measures/corona_data_for_analysis/corona_centrality_data.xlsx',index=False)
influenza_dt.to_excel('outputs/influenza_centrality_measures/influenza_data_for_analysis/influenza_centrality_data.xlsx',index=False)
corona_dt.head()